<h1>Cambio de Password</h1>
<?php View::content() ?>
<fieldset>
	<legend>Introduzca la nueva Password</legend>
	<?php echo Form::open() ?>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Nueva Password</label>
				<?php echo Form::hidden('user.id') ?>
				<?php echo Form::pass('user.password','class="form-control"') ?>
			</div>
		</div>
		<div class="col-md-6">
			
			<div class="form-group">	
				<label>Repetir</label>
				<?php echo Form::pass('user.password2','class="form-control"') ?>
			</div>
		</div>
	</div>
	<?php echo Form::submit('Guardar') ?>
	<?php echo Form::close() ?>
</fieldset>
<br>
<?php echo Html::link('user/',"Lista de Usuarios") ?>