<div class="login_div">
	
	<h1>Inicio de sesion</h1>
	<?php View::content() ?>
	<fieldset>
		<legend>Ingrese sus datos</legend>
		<?php echo Form::open() ?>
		<div class="form-group">
			<label>Username</label>
			<?php echo Form::text('username','class="form-control"') ?>
		</div>
		<div class="form-group">
			<label>Password</label>
			<?php echo Form::pass('password','class="form-control"') ?>
		</div>
		<br>
		<?php echo Form::submit('Ingresar') ?>
		<?php echo Form::button('Crear Usuario','onClick=\'location.href="'.PUBLIC_PATH.'user/create" \'' ) ?>
		<?php echo Form::close() ?>
	</fieldset>
</div>
